"""Backward-compat shim: re-exports from backend.core.tools.code.

The implementation now lives in the :mod:`backend.core.tools.code` subpackage.
This module remains so existing ``from backend.core.tools.code_tools import ...``
imports keep working.
"""
from __future__ import annotations

from .code import *  # noqa: F401,F403  -- re-export public API
from .code import (  # noqa: F401  -- re-export private helpers for legacy attribute access
    _CodeTool,
    _FilePatch,
    _GitIgnoreMatcher,
    _PatchHunk,
    _accept_glob_candidate,
    _apply_file_patch_streaming,
    _apply_simple_unified_patch,
    _compile_python_matcher,
    _consume_expected_lines,
    _decode_output,
    _decode_output_bytes,
    _default_ripgrep_install_dir,
    _detect_output_encoding,
    _emit_tool_observation,
    _error,
    _file_version,
    _find_unique_hunk_offset_streaming,
    _glob_files_python,
    _glob_files_with_rg,
    _glob_for_search_root,
    _glob_has_path_separator,
    _glob_match_texts,
    _glob_payload,
    _grep_files_python,
    _grep_python,
    _grep_with_rg,
    _is_hidden_under,
    _is_match_all_glob,
    _iter_glob_candidates,
    _iter_grep_files,
    _json,
    _looks_like_numbered_read_line,
    _matches_excluded_glob,
    _matches_glob,
    _normalize_glob_pattern,
    _normalize_glob_patterns,
    _number_lines,
    _parse_unified_patch,
    _patch_path,
    _project_root,
    _read_payload,
    _read_targets,
    _resolve_patch_hunk_offsets,
    _resolve_ripgrep_executable,
    _rewrite_patch_stream,
    _rg_json_text,
    _ripgrep_error,
    _ripgrep_failure_reason,
    _ripgrep_platform_dir,
    _search_payload,
    _shape_grep_payload,
    _should_skip_python_path,
    _shell_env,
    _stream_lines_match_at,
    _string_list,
    _strip_line_ending,
    _tool_event_sink,
    _windows_python_c_args,
)
